services:
  - type: web
    name: multimodalai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn multiModalAI.multiModalAI.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "multimodalai.onrender.com"
